# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06df2c617170f375cf09aee5a5f026cf415512baceea2fd44eea2e219cb5ab0dd1dfd74550a1176d17a594edf17ff86679af939637c23995823d100986fed3b8

test:
  secret_key_base: 6cc3e0a52c66d47d7e617175c303a944bda9ff6ab8d8e81e1c9075d43b1fbc0b02c91c9f44aae0357dfc30263f0578e2c4c6b853c2dab97cc626cdfe4139f7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
